In [322]:
import numpy as np
import pandas as pd

In [323]:
# file_path = input("Enter dataset filepath: ")

try:
  # df = pd.read_csv(file_path)
  df = pd.read_csv('./datasets/dataset_train.csv')
except:
  print("File not found!")

In [324]:
df = df.select_dtypes(include=np.number)

In [325]:
class MyNumDataFrame:
    def __init__(self, df):
        df = df.select_dtypes(include=np.number)
        df = df.interpolate(method='linear')
        self.df = df

    def count(self):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            s[col] = len(self.df[col])
        return s

    def mean(self):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            n = len(self.df[col])
            s[col] = np.sum(self.df[col]) / n
        return s

    def median(self):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            n = len(self.df[col])
            values = sorted(self.df[col])
            if n % 2 == 0:
                index = n // 2
                s[col] = (values[index] + values[index - 1]) / 2
            else:
                index = (n - 1) // 2
                s[col] = values[index]
        return s

    def var(self, ddof=1):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            n = len(self.df[col]) - 1
            s[col] = (1 / n) * np.sum((self.df[col] - self.mean()[col]) ** 2)
        return s

    def std(self, ddof=1):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            n = len(self.df[col]) - 1
            s[col] = np.sqrt((1 / n) * np.sum((self.df[col] - self.mean()[col]) ** 2))
        return s

    def min(self):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            s[col] = min(self.df[col])
        return s

    def max(self):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            s[col] = max(self.df[col])
        return s

    def quantile(self, q=0.5):
        s = pd.Series(dtype=object)
        for col in self.df.columns:
            values = sorted(self.df[col])
            index = q * (len(values) - 1) 
            if index.is_integer():
                s[col] = values[int(index)]
            else:
                lower_index = int(index)
                upper_index = lower_index + 1
                lower_value = values[lower_index]
                upper_value = values[upper_index]
                interpolation = lower_value + (upper_value - lower_value) * (index - lower_index)
                s[col] = interpolation
        return s

    def describe(self):
        df = pd.DataFrame(dtype=object, columns=self.df.columns)

        df.loc['count'] = self.count()
        df.loc['mean'] = self.mean()
        df.loc['median'] = self.median()
        df.loc['var'] = self.var()
        df.loc['std'] = self.std()
        df.loc['min'] = self.min()
        df.loc['25%'] = self.quantile(0.25)
        df.loc['50%'] = self.quantile(0.5)
        df.loc['75%'] = self.quantile(0.75)
        df.loc['max'] = self.max()

        return df

my_df = MyNumDataFrame(df)
my_df.describe()

,Index,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
count,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000,1600.00000
mean,799.50000,49586.38687,37.12402,1.14857,-0.39507,3.13447,-222.58866,495.92812,2.95526,1029.92851,5.96371,-0.05445,-243.37441,21.95801
median,799.50000,48975.00000,242.86580,3.44345,-2.49465,4.61300,-415.29279,465.95536,4.36303,1045.40998,5.91477,-0.04824,-244.86777,-2.51500
var,213466.66667,275064977.93028,268218.36012,26.91983,26.85490,17.17629,234022.07585,11197.10190,19.34243,1940.74261,9.85689,0.92850,77.15233,9531.92972
std,462.02453,16585.08299,517.89802,5.18843,5.18217,4.14443,483.75828,105.81636,4.39800,44.05386,3.13957,0.96359,8.78364,97.63160
min,0.00000,-24370.00000,-966.74055,-10.29566,-10.16212,-8.72700,-1086.49683,283.86961,-8.85899,906.62732,-4.69748,-3.31368,-261.04892,-181.47000
25%,399.75000,38514.50000,-489.55139,-4.24779,-5.23790,3.04075,-575.98934,397.90697,2.18562,1025.95304,3.67581,-0.65740,-250.65260,-41.87000
50%,799.50000,48975.00000,242.86580,3.44345,-2.49465,4.61300,-415.29279,465.95536,4.36303,1045.40998,5.91477,-0.04824,-244.86777,-2.51500
75%,1199.25000,60674.75000,519.46886,5.40257,4.88159,5.66625,247.85603,597.37037,5.78429,1058.28506,8.25017,0.57685,-232.55230,50.56000
max,1599.00000,104956.00000,1016.21194,11.61290,9.66741,10.03200,1092.38861,745.39622,11.88971,1098.95820,13.53676,3.05655,-225.42814,279.07000

In [326]:
df.describe()

,Index,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
count,1600.00000,1566.00000,1568.00000,1567.00000,1569.00000,1561.00000,1565.00000,1565.00000,1557.00000,1566.00000,1570.00000,1560.00000,1600.00000,1600.00000
mean,799.50000,49634.57024,39.79713,1.14102,-0.38786,3.15391,-224.58991,495.74797,2.96309,1030.09695,5.95037,-0.05343,-243.37441,21.95801
std,462.02453,16679.80604,520.29827,5.21968,5.21279,4.15530,486.34484,106.28516,4.42577,44.12512,3.14785,0.97146,8.78364,97.63160
min,0.00000,-24370.00000,-966.74055,-10.29566,-10.16212,-8.72700,-1086.49683,283.86961,-8.85899,906.62732,-4.69748,-3.31368,-261.04892,-181.47000
25%,399.75000,38511.50000,-489.55139,-4.30818,-5.25910,3.09900,-577.58010,397.51105,2.21865,1026.20999,3.64679,-0.67161,-250.65260,-41.87000
50%,799.50000,49013.50000,260.28945,3.46901,-2.58934,4.62400,-419.16429,463.91831,4.37818,1045.50700,5.87484,-0.04481,-244.86777,-2.51500
75%,1199.25000,60811.25000,524.77195,5.41918,4.90468,5.66700,254.99486,597.49223,5.82524,1058.43641,8.24817,0.58992,-232.55230,50.56000
max,1599.00000,104956.00000,1016.21194,11.61290,9.66741,10.03200,1092.38861,745.39622,11.88971,1098.95820,13.53676,3.05655,-225.42814,279.07000